// Generated by LiveScript 1.6.0
(function(){
  var Textures, out$ = typeof exports != 'undefined' && exports || this;
  out$.Textures = Textures = (function(){
    Textures.displayName = 'Textures';
    var prototype = Textures.prototype, constructor = Textures;
    function Textures(respname){
      var ref$;
      this.json = {};
      (ref$ = this.json).resource_pack_name == null && (ref$.resource_pack_name = respname);
      this.json.texture_data = {};
    }
    Textures.prototype.set = function(item, path){
      this.json.texture_data[item.icon] = item.texture(path);
      return this;
    };
    Textures.prototype.setJson = function(item, json){
      this.json.texture_data[item.icon] = json;
      return this;
    };
    Textures.prototype.get = function(item){
      return this.json.texture_data[item.icon];
    };
    Textures.prototype.textures = function(){
      return this.json;
    };
    return Textures;
  }());
  out$.textures = textures;
  function textures(it){
    return new Textures(it);
  }
}).call(this);
